name: Auto PR – UI

on:
  issues:
    types: [opened, edited, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  build-ui:
    # Run only for open issues that either start with "Build: " or have the "build-request" label
    if: >
      github.event.issue.state == 'open' &&
      (startsWith(github.event.issue.title, 'Build: ') ||
       contains(join(github.event.issue.labels.*.name, ', '), 'build-request'))
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Safely capture issue title/body (no shell parsing problems)
      - name: Capture issue meta
        id: meta
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
        run: |
          # Save raw text exactly as-is
          printf '%s' "$ISSUE_TITLE" > issue_title.txt
          printf '%s' "$ISSUE_BODY"  > issue_body.txt

          # Parse: "Build: <intent> | <route> | <ui title>"
          INTENT=$(sed -n 's/^Build:[[:space:]]*\([^|]*\).*/\1/p' issue_title.txt | sed 's/[[:space:]]*$//')
          ROUTE=$(awk -F'\\|' '{gsub(/^ +| +$/,"",$2); print $2}' issue_title.txt)
          UITITLE=$(awk -F'\\|' '{gsub(/^ +| +$/,"",$3); print $3}' issue_title.txt)

          echo "intent=$INTENT"   >> $GITHUB_OUTPUT
          echo "route=$ROUTE"     >> $GITHUB_OUTPUT
          echo "uititle=$UITITLE" >> $GITHUB_OUTPUT

      - name: Guard parsed fields
        run: |
          echo "Intent: '${{ steps.meta.outputs.intent }}'"
          echo "Route:  '${{ steps.meta.outputs.route }}'"
          echo "Title:  '${{ steps.meta.outputs.uititle }}'"
          test -n "${{ steps.meta.outputs.intent }}" || (echo "Missing intent in title"; exit 1)
          test -n "${{ steps.meta.outputs.route }}"  || (echo "Missing route in title"; exit 1)

      - name: Scaffold UI (page + plan)
        run: |
          mkdir -p ops
          # Store the issue body verbatim (no special chars problems)
          cat > ops/ui-plan-${{ steps.meta.outputs.route || 'unknown' }}.md <<'MD'
          ${{ github.event.issue.body }}
          MD

          # Make the page if it doesn't exist
          PAGE_DIR="app/${{ steps.meta.outputs.route }}"
          mkdir -p "$PAGE_DIR"
          if [ ! -f "$PAGE_DIR/page.tsx" ]; then
            cat > "$PAGE_DIR/page.tsx" <<'TSX'
            "use client";
            import React from "react";

            export default function Page() {
              return (
                <div className="p-6 space-y-3">
                  <h1 className="text-2xl font-bold">Coming soon</h1>
                  <p>This tab will render data from the backend for this route.</p>
                </div>
              );
            }
            TSX
          fi

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ format('auto/ui-{0}', github.run_id) }}
          base: main
          commit-message: "feat(ui): scaffold ${{ steps.meta.outputs.route }} from issue #${{ github.event.issue.number }}"
          title: "PR: ${{ steps.meta.outputs.route }} — build from issue #${{ github.event.issue.number }}"
          body: |
            Auto-generated from issue #${{ github.event.issue.number }}.
            Intent: ${{ steps.meta.outputs.intent }}
            Route:  ${{ steps.meta.outputs.route }}
          labels: automated
