name: CI Frontend

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - 'app/**'
      - 'lib/**'
      - 'package.json'
      - 'tsconfig.json'
      - '.github/workflows/ci-frontend.yml'
  push:
    branches: [ ci-seed-1 ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Typecheck & build
        env:
          NEXT_PUBLIC_BACKEND_URL: https://lightsignal-backend.onrender.com
        run: npm run build
